{% set name = "pathos" %}
{% set version = "0.2.1" %}

package:
  name: pathos
  version: {{ version }}

source:
  fn: pathos-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip 
  md5: d4405b588d7a23ef919fe19527b3fa88

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - ppft >=1.6.4.5
    - dill >=0.2.5
    - pox >=0.2.2
    - multiprocess >=0.70.4

  run:
    - python
    - ppft >=1.6.4.5
    - dill >=0.2.5
    - pox >=0.2.2
    - multiprocess >=0.70.4

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing

extra:
  recipe-maintainers:
    - jschueller
