{% set name = "pathos" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bad4912d0ef865654a7cc478da65f2e1d5b69f3d92c4a7d9c9845657783c0754

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - dill
    - multiprocess
    - ppft
    - pox
  run:
    - python
    - dill >=0.4.0
    - multiprocess >=0.70.18
    - pox >=0.3.6
    - ppft >=1.7.7

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  description: |
    Pathos is a framework for heterogenous computing. It primarily provides the
    communication mechanisms for configuring and launching parallel computations
    across heterogenous resources. Pathos provides stagers and launchers for
    parallel and distributed computing, where each launcher contains the syntactic
    logic to configure and launch jobs in an execution environment.
  dev_url: https://github.com/uqfoundation/pathos
  doc_url: https://mmckerns.github.io/project/pathos/wiki.html

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
