{% set name = "pathos" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 1f0f27a90f7ab66c423ba796529000fde9360d17b2d8e50097641ff405fc6f15

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
  run:
    - dill >=0.3.4
    - multiprocess >=0.70.12
    - pox >=0.3.0
    - ppft >=1.6.6.4
    - python =2.7|>=3.6

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  dev_url: https://github.com/uqfoundation/pathos

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
