{% set name = "pathos" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24fa8db51fbd9284da8e191794097c4bb2aa3fce411090e57af6385e61b97e09

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - dill >=0.3.7
    - multiprocess >=0.70.15
    - pox >=0.3.3
    - ppft >=1.7.6.7

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  description: |
    Pathos is a framework for heterogenous computing. It primarily provides the 
    communication mechanisms for configuring and launching parallel computations
    across heterogenous resources. Pathos provides stagers and launchers for 
    parallel and distributed computing, where each launcher contains the syntactic 
    logic to configure and launch jobs in an execution environment. 
  dev_url: https://github.com/uqfoundation/pathos
  doc_url: https://mmckerns.github.io/project/pathos/wiki.html

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
