{% set name = "pathos" %}
{% set version = "0.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 954c5b0a8b257c375e35d311c65fa62a210a3d65269195557de38418ac9f61f9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - dill >=0.2.9
    - multiprocess >=0.70.7
    - pox >=0.2.5
    - ppft >=1.6.4.9
    - python

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
