# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sBNtTvgLHPGrr9KpdxovHbqxkAtFINBpttX2jXxwqIUo3Pr93XFgbzrLUZXMpszLU44ZzrKVbRktFv4v/fsS0fmxbJryqp++HKnMIib/TXkV8GSd/8kACdVL6Pi3ecoa3GKHdkVpPHIaN8uKFm+PHAYixajELk42gC2xp500yNxM5KBK/nUsXmfuUvKnj6XGiSFmb8nfz2mZIXKptFgnzImab0Anwl5g+UgCpJPqQHLiOIvNIl/TYI0/PBZXzX7PZUN1hGBjopzMMJjmbmktCac+7agwLUH7cVArqaEEojguKb3IGy/9zgcYbj/mkdzMeaR8OjU9nj81M3mbNsrZr4Fkwor/SgJF3wWHuPgSBPic+M8sUYWmUZO1PP1X2CPJ2dA7iySA0Bb+7AexRkfpMu++MsAgUQ7XTBL04MLchZNmMPHQhHT7PdvaY8LY+PAa7QAMPfDfQbz6JbMrL345O/mebLeBnsJD30snUTrA/JwCd78LvNzG6c6/X9jMInXhqauAQ1iPg+ySCqDc/iUNBDtlf3HpJGCTu5lXPvMXOnSfU5Qm8IGA6gC/xEtATr6ZzbLapH+QNkPY2RDBmOskfss0cN+H6BWqhWV4+JTyWmsSs1KSnOHirflgXYjlvcqZUnUvWBxC2yh7QoU1ZNfpN+48p0n299+afcre/4hnT9I="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
