travis:
  secure:
    BINSTAR_TOKEN: k6/LNh9VwemoMlmfP82uEBGAMZo3JE5mlA3CN0Cuah/S8rNY6PvlpYRFFU5eBL2GWY7YOGrf7OD8enoQPIvx/t4Tv55+5qHTSXJcYmeQs5n8EZmUQalqy5SIWpWS0E5jpatca4Pxb0DlkXHcZjXfoRqfD9YJSkQpyPmEY1xBIu6jjnCS+jsjvyXc+w3+jXFrj08QYceM1wo7RJuhgcAgO969gpmpnac/qySzwJ/Hqs/Sjf0yVZNh/hQzLgJI61XpilwARFBbyVe2giRq4wLPLnVd5ILTcV7CXqEsxv3YKUNLf3U+vv03BKsL6A7/1HFrGld4wE+0gu0AG/JPtP2qhuD0gee52Y4ntmijFhCs1KU0mW1Ad7Ff6PmgRv/ouy3GiS2zvVWSj3oaMgtft2H0OuVjyWqLrtOoHFvIUm0CjJ1PqK7fVhCzxkkGHfpK6LMEnnXakpZcqHGIGKIweO+MJYmbleduiejzpLZ36ihPbPJCxJMBlKeg8trPzzrtQapnFKyEAHTNBNyjTgCbb0FljkKlR/CPndBfMpiIcWzrgqLuepgojdiTe6UjHC3GmnMLscmGsN9NlYsw3DkV5Sx792q0IQtgwXC/29CZm2ViNVk6YDnzGnVX/ALxZzS1SMrD5gmoDtDY1vw72Kfnpp89T1cHO0B46Rc5cTtSQC8DH5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
