travis:
  secure:
    BINSTAR_TOKEN: r3WUKAS0mADsrPDxk4kpJDsSlh8dnEuTu9+MyokKCYzeiRdt6vT+P1zB9xvkvjV1OkYHkScMrg3+/aT3MTDQTJR7pxk0G8e8iNWald558K5zSEu8DqGk9d8Gf0LLPotVsXgVo1923opbQchEq6AzXOvg9uY1bQVm2FMt68rm4Zgg91cz1hdHNXuxLra/Ny24cTpwn/nbFhzQe2+Mc6pIFu16rcol0kGRR7gzm8uwqzUZ7LDm3Qb+sOTgXcAvE1oBiRxo6eFUGXcrn2wuBDP4zcWurZBOeWH8po0dWtjfGJpcIZhLqZjlBA9kzeVE5KHYuGg7yPPlf6gi4TVeuJ++F6OYm9wDL6AlqfIR1Hr6lnTXo5SQp09sfxqMPXqsJslyvyX5UchxuGYoGlCWgXK+jAffX7Zu9vvWICqV8PjFlcQS1jE2NXBJqFi1YxaJGg2RRR90n8HtXH/JEQoWiih9wmNga97E2tPmui20LxdXWpSsm8tOarqe+RAngxQF8L4cb7uo0z4sTLt9xuqH1JM/CIEy9GpP06Sn+vCRnzouSudGZ/donTK5voQWH2Tk4VRp7OXt6uT8HxQoZcxpxRJKalXOCccWMUIbRRZpIsZuH8Vbqq+LQUvsVQEoRMFpPNh3vbsEGZeTU1asyGFBCTVU0BzgiCurkJiRwTdUugyPkWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
